name: Check for new Grpc release

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest

    outputs:
      latest-release: ${{ steps.latest.outputs.LATEST_RELEASE }}
      current-release: ${{ steps.current.outputs.CURRENT_RELEASE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl jq

      - name: Get latest Grpc release
        id: latest
        run: |
          GRPC_LATEST=$(curl -s https://pypi.org/pypi/grpcio/json | jq -r '.info.version')
          echo "LATEST_RELEASE=$GRPC_LATEST" >> $GITHUB_OUTPUT
          echo "Latest Grpc version: "$GRPC_LATEST

      - name: Get current Grpc release for Power
        id: current
        run: |
          GRPC_CURRENT=$(curl -s https://api.github.com/repos/DahlitzFlorian/oss-ecosystem-grpc/releases/latest | grep tag_name | cut -d '"' -f4)
          echo "CURRENT_RELEASE=$GRPC_CURRENT" >> $GITHUB_OUTPUT
          echo "Current Grpc version on Power: "$GRPC_CURRENT

  build-new-release:
    needs: [check-release]
    if: needs.check-release.outputs.latest-release != needs.check-release.outputs.current-release
    uses: ./.github/workflows/build_grpc.yaml
    with:
      release: ${{ needs.check-release.outputs.latest-release }}
